INSERT INTO persons (FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER) VALUES ('Julia', 'Petrova', '1995-11-25', 'F');
INSERT INTO persons (FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER) VALUES ('Artur', 'Petrov', '2017-03-01', 'M');
INSERT INTO persons (FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER) VALUES ('Viktor', 'Petrov', '1990-03-31', 'M');
