CREATE TABLE users
  (
     USER_ID          UUID         NOT NULL PRIMARY KEY DEFAULT uuid_generate_v1(),
     USER_LOGIN       VARCHAR(128) NOT NULL UNIQUE,
     USER_PASSWORD    VARCHAR(128) NOT NULL,
     USER_EMAIL       VARCHAR(128) NOT NULL,
     USER_PHONE       VARCHAR(128) NOT NULL,
     CREATION_DATE    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
     IS_ACTIVE        BOOLEAN      NOT NULL DEFAULT TRUE
  );